name: Scrape Breweries

on:
  schedule:
    - cron: "0 */12 * * *"   # Run every 12 hours
  workflow_dispatch:         # Allow manual runs from the Actions tab

permissions:
  contents: write            # allow this workflow to push commits

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install scraper dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run 1700 scraper
        run: |
          python scrapers/scrape_1700.py

      - name: Run Billsburg scraper
        run: |
          python scrapers/scrape_billsburg.py


      - name: List files after scraper
        run: |
          echo "DEBUG: files in workspace after scraper:"
          ls -la

      - name: Merge brewery JSON files into beers.json
  run: |
    python - << 'EOF'
    import json, pathlib

    root = pathlib.Path(".")
    files = [
        root / "beers_1700.json",
        root / "beers_billsburg.json",
    ]

    all_beers = []
    for path in files:
        if path.exists():
            with path.open("r", encoding="utf-8") as f:
                try:
                    data = json.load(f)
                    if isinstance(data, list):
                        all_beers.extend(data)
                except json.JSONDecodeError:
                    print(f"WARNING: could not parse {path}, skipping")

    with open("beers.json", "w", encoding="utf-8") as out:
        json.dump(all_beers, out, indent=2, ensure_ascii=False)

    print(f"Wrote {len(all_beers)} beers to beers.json")
    EOF



      - name: Commit and push updated beers.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Local Beer App Bot"
          git config user.email "bot@example.com"

          # show status for debugging
          git status

          # stage file
          git add beers.json

          # commit if there are changes; otherwise do nothing
          git commit -m "Update beers.json from scraper" || echo "No changes to commit"

          # push using the token-based remote set up by actions/checkout
          git push
